import express from 'express';
import { addAdmin, adminLogin, adminRegister, getAdmin, getAdmins, getTotal } from '../controller/admin.controller';
import { getAdminAuth, supAdminAuth } from '../middleware';
import adminAuth from '../middleware/adminAuth';
const adminRouter = express.Router();
adminRouter.post('/register', adminRegister);
adminRouter.post('/login', adminLogin);
adminRouter.post('/add', supAdminAuth, addAdmin);
adminRouter.get('/getUser', getAdmin);
adminRouter.get('/all', supAdminAuth, getAdmins);
adminRouter.get('/total', adminAuth, getTotal);
export default adminRouter;
