import express from 'express';
import { addTeacher, getTeacher, getTeachers, teacherLogin, teacherRegister } from '../controller/teacher.controller';
import adminAuth from '../middleware/adminAuth';
const teacherRouter = express.Router();
teacherRouter.post('/register', teacherRegister);
teacherRouter.post('/login', teacherLogin);
teacherRouter.post('/add', adminAuth, addTeacher);
teacherRouter.get('/getUser', getTeacher);
teacherRouter.get('/all', getTeachers);
export default teacherRouter;
